### ISSUE TITLE
Vertex id seems to never get initialized

### ISSUE THREAD

**Issue by IgnoreWarnings** [VILLASframework/common#89]
file: vertex.hpp
problem: Vertex id  never gets initialized
solution proposal: static member to hold next free id and increment  and assignment in constructor
observations:
- id is private
- no setter
- no inheritance
- id used by serval methods but read only

**Comment by IgnoreWarnings** [comment]
should be moved to the submodule common.

**Comment by stv0g** [comment]
This is the member variable in question:

https://github.com/VILLASframework/common/blob/618804a1d91a15adab53f39729fe5e1b1e4e7731/include/villas/graph/vertex.hpp#L38

**Comment by stv0g** [comment]
The vertex id must be unique **per graph** not globally.

So there is a `lastVertexId` in `directed.hpp` which gets set in the `Vertex` here:

https://github.com/VILLASframework/common/blob/618804a1d91a15adab53f39729fe5e1b1e4e7731/include/villas/graph/directed.hpp#L90

**Comment by Stapelueberflieger** [comment]
Thanks for insight. This however breaks encapsulation, since the member is declared private and accessed via pointer.

**Comment by Stapelueberflieger** [comment]
Since its not unique per vertex, I will just initialize default value in header.

**Comment by stv0g** [comment]
> This however breaks encapsulation, since the member is declared private and accessed via pointer.

Can you elaborate on this?

I think vertices must only be created by `DirectedGraph:: addVertex()`. Maybe we should declare its constructor private..

**Comment by IgnoreWarnings** [comment]
the member id is declared private 
https://github.com/VILLASframework/common/blob/618804a1d91a15adab53f39729fe5e1b1e4e7731/include/villas/graph/vertex.hpp#L37-L38
and accessed via pointer.

**Comment by IgnoreWarnings** [comment]
3360a9fea003e3db76e1cc906215d200d7eb6ce1

**Comment by stv0g** [comment]
> the member id is declared private

This is okay as the graph class is a friend of the vertex
